spring.application.name=gateway-pagamento

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5433/gatewaydb
spring.datasource.username=gateway
spring.datasource.password=gateway
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway (geralmente o default já basta, mas deixa explícito)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

# ===== Resilience4j: Webhook Delivery =====

# Circuit Breaker
resilience4j.circuitbreaker.instances.webhookDelivery.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.webhookDelivery.slidingWindowSize=20
resilience4j.circuitbreaker.instances.webhookDelivery.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.webhookDelivery.failureRateThreshold=50
resilience4j.circuitbreaker.instances.webhookDelivery.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.webhookDelivery.permittedNumberOfCallsInHalfOpenState=5

# Retry (rápido, dentro da mesma tentativa de envio)
resilience4j.retry.instances.webhookDelivery.maxAttempts=3
resilience4j.retry.instances.webhookDelivery.waitDuration=200ms

# TimeLimiter (timeout por envio)
resilience4j.timelimiter.instances.webhookDelivery.timeoutDuration=3s